
// This file is automatically generated

export const METADATA = {
  "name": "@openai/agents-openai",
  "version": "0.14.0",
  "versions": {
    "@openai/agents-openai": "0.14.0",
    "@openai/agents-core": "workspace:*",
    "openai": "^6.46.0"
  }
};

export default METADATA;
